/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendenteRouteImport } from './routes/pendente'
import { Route as BloqueadoRouteImport } from './routes/bloqueado'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVeiculosRouteImport } from './routes/app.veiculos'
import { Route as AppServicosRouteImport } from './routes/app.servicos'
import { Route as AppSelecionarUnidadeRouteImport } from './routes/app.selecionar-unidade'
import { Route as AppPecasRouteImport } from './routes/app.pecas'
import { Route as AppOrdensRouteImport } from './routes/app.ordens'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppColaboradoresRouteImport } from './routes/app.colaboradores'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppOrdensIdRouteImport } from './routes/app.ordens.$id'
import { Route as AppFinanceiroContasPagarRouteImport } from './routes/app.financeiro.contas-pagar'
import { Route as AppAdminOficinasRouteImport } from './routes/app.admin.oficinas'
import { Route as AppAdminFinanceiroRouteImport } from './routes/app.admin.financeiro'
import { Route as AppAdminContasRouteImport } from './routes/app.admin.contas'
import { Route as AppAdminConfiguracoesRouteImport } from './routes/app.admin.configuracoes'
import { Route as AppOrdensIdImprimirRouteImport } from './routes/app.ordens.$id.imprimir'
import { Route as ApiPublicHooksFipeSyncRouteImport } from './routes/api/public/hooks/fipe-sync'

const PendenteRoute = PendenteRouteImport.update({
  id: '/pendente',
  path: '/pendente',
  getParentRoute: () => rootRouteImport,
} as any)
const BloqueadoRoute = BloqueadoRouteImport.update({
  id: '/bloqueado',
  path: '/bloqueado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVeiculosRoute = AppVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AppRoute,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppRoute,
} as any)
const AppSelecionarUnidadeRoute = AppSelecionarUnidadeRouteImport.update({
  id: '/selecionar-unidade',
  path: '/selecionar-unidade',
  getParentRoute: () => AppRoute,
} as any)
const AppPecasRoute = AppPecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensRoute = AppOrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppColaboradoresRoute = AppColaboradoresRouteImport.update({
  id: '/colaboradores',
  path: '/colaboradores',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensIdRoute = AppOrdensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppOrdensRoute,
} as any)
const AppFinanceiroContasPagarRoute =
  AppFinanceiroContasPagarRouteImport.update({
    id: '/contas-pagar',
    path: '/contas-pagar',
    getParentRoute: () => AppFinanceiroRoute,
  } as any)
const AppAdminOficinasRoute = AppAdminOficinasRouteImport.update({
  id: '/admin/oficinas',
  path: '/admin/oficinas',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminFinanceiroRoute = AppAdminFinanceiroRouteImport.update({
  id: '/admin/financeiro',
  path: '/admin/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminContasRoute = AppAdminContasRouteImport.update({
  id: '/admin/contas',
  path: '/admin/contas',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminConfiguracoesRoute = AppAdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdensIdImprimirRoute = AppOrdensIdImprimirRouteImport.update({
  id: '/imprimir',
  path: '/imprimir',
  getParentRoute: () => AppOrdensIdRoute,
} as any)
const ApiPublicHooksFipeSyncRoute = ApiPublicHooksFipeSyncRouteImport.update({
  id: '/api/public/hooks/fipe-sync',
  path: '/api/public/hooks/fipe-sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/bloqueado': typeof BloqueadoRoute
  '/pendente': typeof PendenteRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/colaboradores': typeof AppColaboradoresRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/app/ordens': typeof AppOrdensRouteWithChildren
  '/app/pecas': typeof AppPecasRoute
  '/app/selecionar-unidade': typeof AppSelecionarUnidadeRoute
  '/app/servicos': typeof AppServicosRoute
  '/app/veiculos': typeof AppVeiculosRoute
  '/app/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/app/admin/contas': typeof AppAdminContasRoute
  '/app/admin/financeiro': typeof AppAdminFinanceiroRoute
  '/app/admin/oficinas': typeof AppAdminOficinasRoute
  '/app/financeiro/contas-pagar': typeof AppFinanceiroContasPagarRoute
  '/app/ordens/$id': typeof AppOrdensIdRouteWithChildren
  '/api/public/hooks/fipe-sync': typeof ApiPublicHooksFipeSyncRoute
  '/app/ordens/$id/imprimir': typeof AppOrdensIdImprimirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/bloqueado': typeof BloqueadoRoute
  '/pendente': typeof PendenteRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/colaboradores': typeof AppColaboradoresRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/app/ordens': typeof AppOrdensRouteWithChildren
  '/app/pecas': typeof AppPecasRoute
  '/app/selecionar-unidade': typeof AppSelecionarUnidadeRoute
  '/app/servicos': typeof AppServicosRoute
  '/app/veiculos': typeof AppVeiculosRoute
  '/app/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/app/admin/contas': typeof AppAdminContasRoute
  '/app/admin/financeiro': typeof AppAdminFinanceiroRoute
  '/app/admin/oficinas': typeof AppAdminOficinasRoute
  '/app/financeiro/contas-pagar': typeof AppFinanceiroContasPagarRoute
  '/app/ordens/$id': typeof AppOrdensIdRouteWithChildren
  '/api/public/hooks/fipe-sync': typeof ApiPublicHooksFipeSyncRoute
  '/app/ordens/$id/imprimir': typeof AppOrdensIdImprimirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/bloqueado': typeof BloqueadoRoute
  '/pendente': typeof PendenteRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/colaboradores': typeof AppColaboradoresRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/financeiro': typeof AppFinanceiroRouteWithChildren
  '/app/ordens': typeof AppOrdensRouteWithChildren
  '/app/pecas': typeof AppPecasRoute
  '/app/selecionar-unidade': typeof AppSelecionarUnidadeRoute
  '/app/servicos': typeof AppServicosRoute
  '/app/veiculos': typeof AppVeiculosRoute
  '/app/admin/configuracoes': typeof AppAdminConfiguracoesRoute
  '/app/admin/contas': typeof AppAdminContasRoute
  '/app/admin/financeiro': typeof AppAdminFinanceiroRoute
  '/app/admin/oficinas': typeof AppAdminOficinasRoute
  '/app/financeiro/contas-pagar': typeof AppFinanceiroContasPagarRoute
  '/app/ordens/$id': typeof AppOrdensIdRouteWithChildren
  '/api/public/hooks/fipe-sync': typeof ApiPublicHooksFipeSyncRoute
  '/app/ordens/$id/imprimir': typeof AppOrdensIdImprimirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/bloqueado'
    | '/pendente'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/colaboradores'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/financeiro'
    | '/app/ordens'
    | '/app/pecas'
    | '/app/selecionar-unidade'
    | '/app/servicos'
    | '/app/veiculos'
    | '/app/admin/configuracoes'
    | '/app/admin/contas'
    | '/app/admin/financeiro'
    | '/app/admin/oficinas'
    | '/app/financeiro/contas-pagar'
    | '/app/ordens/$id'
    | '/api/public/hooks/fipe-sync'
    | '/app/ordens/$id/imprimir'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/bloqueado'
    | '/pendente'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/colaboradores'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/financeiro'
    | '/app/ordens'
    | '/app/pecas'
    | '/app/selecionar-unidade'
    | '/app/servicos'
    | '/app/veiculos'
    | '/app/admin/configuracoes'
    | '/app/admin/contas'
    | '/app/admin/financeiro'
    | '/app/admin/oficinas'
    | '/app/financeiro/contas-pagar'
    | '/app/ordens/$id'
    | '/api/public/hooks/fipe-sync'
    | '/app/ordens/$id/imprimir'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/bloqueado'
    | '/pendente'
    | '/app/agenda'
    | '/app/clientes'
    | '/app/colaboradores'
    | '/app/configuracoes'
    | '/app/dashboard'
    | '/app/financeiro'
    | '/app/ordens'
    | '/app/pecas'
    | '/app/selecionar-unidade'
    | '/app/servicos'
    | '/app/veiculos'
    | '/app/admin/configuracoes'
    | '/app/admin/contas'
    | '/app/admin/financeiro'
    | '/app/admin/oficinas'
    | '/app/financeiro/contas-pagar'
    | '/app/ordens/$id'
    | '/api/public/hooks/fipe-sync'
    | '/app/ordens/$id/imprimir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BloqueadoRoute: typeof BloqueadoRoute
  PendenteRoute: typeof PendenteRoute
  ApiPublicHooksFipeSyncRoute: typeof ApiPublicHooksFipeSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pendente': {
      id: '/pendente'
      path: '/pendente'
      fullPath: '/pendente'
      preLoaderRoute: typeof PendenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloqueado': {
      id: '/bloqueado'
      path: '/bloqueado'
      fullPath: '/bloqueado'
      preLoaderRoute: typeof BloqueadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/veiculos': {
      id: '/app/veiculos'
      path: '/veiculos'
      fullPath: '/app/veiculos'
      preLoaderRoute: typeof AppVeiculosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/servicos': {
      id: '/app/servicos'
      path: '/servicos'
      fullPath: '/app/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/selecionar-unidade': {
      id: '/app/selecionar-unidade'
      path: '/selecionar-unidade'
      fullPath: '/app/selecionar-unidade'
      preLoaderRoute: typeof AppSelecionarUnidadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pecas': {
      id: '/app/pecas'
      path: '/pecas'
      fullPath: '/app/pecas'
      preLoaderRoute: typeof AppPecasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ordens': {
      id: '/app/ordens'
      path: '/ordens'
      fullPath: '/app/ordens'
      preLoaderRoute: typeof AppOrdensRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/colaboradores': {
      id: '/app/colaboradores'
      path: '/colaboradores'
      fullPath: '/app/colaboradores'
      preLoaderRoute: typeof AppColaboradoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ordens/$id': {
      id: '/app/ordens/$id'
      path: '/$id'
      fullPath: '/app/ordens/$id'
      preLoaderRoute: typeof AppOrdensIdRouteImport
      parentRoute: typeof AppOrdensRoute
    }
    '/app/financeiro/contas-pagar': {
      id: '/app/financeiro/contas-pagar'
      path: '/contas-pagar'
      fullPath: '/app/financeiro/contas-pagar'
      preLoaderRoute: typeof AppFinanceiroContasPagarRouteImport
      parentRoute: typeof AppFinanceiroRoute
    }
    '/app/admin/oficinas': {
      id: '/app/admin/oficinas'
      path: '/admin/oficinas'
      fullPath: '/app/admin/oficinas'
      preLoaderRoute: typeof AppAdminOficinasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/financeiro': {
      id: '/app/admin/financeiro'
      path: '/admin/financeiro'
      fullPath: '/app/admin/financeiro'
      preLoaderRoute: typeof AppAdminFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/contas': {
      id: '/app/admin/contas'
      path: '/admin/contas'
      fullPath: '/app/admin/contas'
      preLoaderRoute: typeof AppAdminContasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin/configuracoes': {
      id: '/app/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/app/admin/configuracoes'
      preLoaderRoute: typeof AppAdminConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ordens/$id/imprimir': {
      id: '/app/ordens/$id/imprimir'
      path: '/imprimir'
      fullPath: '/app/ordens/$id/imprimir'
      preLoaderRoute: typeof AppOrdensIdImprimirRouteImport
      parentRoute: typeof AppOrdensIdRoute
    }
    '/api/public/hooks/fipe-sync': {
      id: '/api/public/hooks/fipe-sync'
      path: '/api/public/hooks/fipe-sync'
      fullPath: '/api/public/hooks/fipe-sync'
      preLoaderRoute: typeof ApiPublicHooksFipeSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppFinanceiroRouteChildren {
  AppFinanceiroContasPagarRoute: typeof AppFinanceiroContasPagarRoute
}

const AppFinanceiroRouteChildren: AppFinanceiroRouteChildren = {
  AppFinanceiroContasPagarRoute: AppFinanceiroContasPagarRoute,
}

const AppFinanceiroRouteWithChildren = AppFinanceiroRoute._addFileChildren(
  AppFinanceiroRouteChildren,
)

interface AppOrdensIdRouteChildren {
  AppOrdensIdImprimirRoute: typeof AppOrdensIdImprimirRoute
}

const AppOrdensIdRouteChildren: AppOrdensIdRouteChildren = {
  AppOrdensIdImprimirRoute: AppOrdensIdImprimirRoute,
}

const AppOrdensIdRouteWithChildren = AppOrdensIdRoute._addFileChildren(
  AppOrdensIdRouteChildren,
)

interface AppOrdensRouteChildren {
  AppOrdensIdRoute: typeof AppOrdensIdRouteWithChildren
}

const AppOrdensRouteChildren: AppOrdensRouteChildren = {
  AppOrdensIdRoute: AppOrdensIdRouteWithChildren,
}

const AppOrdensRouteWithChildren = AppOrdensRoute._addFileChildren(
  AppOrdensRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppClientesRoute: typeof AppClientesRoute
  AppColaboradoresRoute: typeof AppColaboradoresRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFinanceiroRoute: typeof AppFinanceiroRouteWithChildren
  AppOrdensRoute: typeof AppOrdensRouteWithChildren
  AppPecasRoute: typeof AppPecasRoute
  AppSelecionarUnidadeRoute: typeof AppSelecionarUnidadeRoute
  AppServicosRoute: typeof AppServicosRoute
  AppVeiculosRoute: typeof AppVeiculosRoute
  AppAdminConfiguracoesRoute: typeof AppAdminConfiguracoesRoute
  AppAdminContasRoute: typeof AppAdminContasRoute
  AppAdminFinanceiroRoute: typeof AppAdminFinanceiroRoute
  AppAdminOficinasRoute: typeof AppAdminOficinasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppClientesRoute: AppClientesRoute,
  AppColaboradoresRoute: AppColaboradoresRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFinanceiroRoute: AppFinanceiroRouteWithChildren,
  AppOrdensRoute: AppOrdensRouteWithChildren,
  AppPecasRoute: AppPecasRoute,
  AppSelecionarUnidadeRoute: AppSelecionarUnidadeRoute,
  AppServicosRoute: AppServicosRoute,
  AppVeiculosRoute: AppVeiculosRoute,
  AppAdminConfiguracoesRoute: AppAdminConfiguracoesRoute,
  AppAdminContasRoute: AppAdminContasRoute,
  AppAdminFinanceiroRoute: AppAdminFinanceiroRoute,
  AppAdminOficinasRoute: AppAdminOficinasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BloqueadoRoute: BloqueadoRoute,
  PendenteRoute: PendenteRoute,
  ApiPublicHooksFipeSyncRoute: ApiPublicHooksFipeSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
